name: Debug URL Format

on:
  workflow_dispatch: # Manual trigger only

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Test Different URL Formats
        run: |
          echo "🔍 Testing different URL formats..."
          echo "Secret value length: ${#VERCEL_APP_URL}"
          echo "Secret starts with https: $(echo $VERCEL_APP_URL | grep -q '^https://' && echo 'YES' || echo 'NO')"
          echo "Secret ends with slash: $(echo $VERCEL_APP_URL | grep -q '/$' && echo 'YES' || echo 'NO')"
          
          # Test exact format
          echo "Testing: $VERCEL_APP_URL/api/cron/update"
          curl -X POST "$VERCEL_APP_URL/api/cron/update" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $CRON_SECRET" \
            -w "\nStatus: %{http_code}\n" \
            -v
        env:
          VERCEL_APP_URL: ${{ secrets.VERCEL_APP_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
